/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.12 public/models/flower.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Flower(props) {
  const { nodes, materials } = useGLTF('/models/flower.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.494, 0]} scale={0.125}>
        <mesh geometry={nodes.Cube002.geometry} material={materials.flower} />
        <mesh geometry={nodes.Cube002_1.geometry} material={materials['flower-part']} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/flower.glb')
