/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.12 public/models/star.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Star(props) {
  const { nodes, materials } = useGLTF('/models/star.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder.geometry} material={materials.star} position={[0, 0.486, 0]} rotation={[Math.PI / 2, 0, 0]} scale={[0.96, 0.378, 0.96]} />
    </group>
  )
}

useGLTF.preload('/models/star.glb')
